import {
  SETTINGS_SCHEMA,
  defaultsOf,
  describeSchema,
  resolve,
} from "tether/index.js";

/**
 * Everything a GraphView can be told, as one schema: type, range, default, label and hint for each option. Pass any
 * subset to the constructor or to setOptions(); they're checked (bad values are clamped or replaced by the default,
 * with a warning, or throw with `strict: true`). Layout and physics options (Tether's settings: layout, direction,
 * layered, physicsMode, the forces) take effect on the next render(); everything else at once.
 *
 * OPTIONS (the list, for settings UIs) and DEFAULT_OPTIONS come from this schema.
 */

/** @returns {import('tether/index.js').Field} */
const number = (group, label, value, min, max, step, hint) => ({
  type: "number",
  group,
  label,
  default: value,
  min,
  max,
  step,
  hint,
});
/** @returns {import('tether/index.js').Field} */
const integer = (group, label, value, min, max, step, hint) => ({
  ...number(group, label, value, min, max, step, hint),
  type: "integer",
});
/** @returns {import('tether/index.js').Field} */
const boolean = (group, label, value, hint) => ({
  type: "boolean",
  group,
  label,
  default: value,
  hint,
});
/** @returns {import('tether/index.js').Field} */
const choice = (group, label, value, values, hint, open = false) => ({
  type: "enum",
  group,
  label,
  default: value,
  values,
  open,
  hint,
});

/** @type {Readonly<import('tether/index.js').Schema>} */
export const OPTIONS_SCHEMA = Object.freeze({
  // ---------------------------------------------------------------- layout and physics (Tether)
  ...SETTINGS_SCHEMA,

  // ---------------------------------------------------------------- nodes
  nodeSize: number(
    "Nodes",
    "Node size",
    48,
    4,
    400,
    1,
    "Base width and height of a node, in graph units (before nodeSizeScale).",
  ),
  nodeSizeScale: number(
    "Nodes",
    "Node size ×",
    1,
    0.2,
    4,
    0.05,
    "Multiplies every node's size.",
  ),
  rootSizeScale: number(
    "Nodes",
    "Root size ×",
    1.35,
    0.5,
    4,
    0.05,
    "The root is this much bigger than other nodes.",
  ),
  nodeShape: choice(
    "Nodes",
    "Shape",
    "round-rectangle",
    [
      "round-rectangle",
      "rectangle",
      "ellipse",
      "hexagon",
      "octagon",
      "diamond",
      "round-diamond",
    ],
    "A built-in shape, or one added with registerNodeShape().",
    true,
  ),
  tintNodeFill: boolean(
    "Nodes",
    "Tinted fill",
    false,
    "Fill nodes with a tint of their colour instead of the theme's node fill.",
  ),
  tintFillAlpha: number(
    "Nodes",
    "Tint strength",
    0.3,
    0,
    1,
    0.01,
    "How opaque the tinted fill is.",
  ),
  nodeBorderWidth: number(
    "Nodes",
    "Border width",
    3,
    0,
    20,
    0.5,
    "Node border width, in graph units.",
  ),
  rootBorderBoost: number(
    "Nodes",
    "Root border +",
    1.5,
    0,
    10,
    0.5,
    "The root's border is this much thicker.",
  ),
  showIcons: boolean(
    "Nodes",
    "Icons",
    true,
    "Draw each node's icon (its `icon` URL).",
  ),

  // ---------------------------------------------------------------- cards
  nodeLook: choice(
    "Cards",
    "Nodes as",
    "icon",
    ["icon", "card"],
    '"icon": square nodes with their label beside them. "card": wide cards with the text inside (title, subtitle, value, tag), a colour stripe and port dots. Switching morphs the graph and lays it out again.',
  ),
  cardWidth: number(
    "Cards",
    "Card width",
    222,
    60,
    1000,
    1,
    "Card width, in graph units.",
  ),
  cardHeight: number(
    "Cards",
    "Card height",
    64,
    24,
    400,
    1,
    "Card height, in graph units.",
  ),
  cardIconSize: number(
    "Cards",
    "Card icon",
    28,
    0,
    200,
    1,
    "The icon's size on a card (0: no icon).",
  ),
  cardIconInset: number(
    "Cards",
    "Card icon inset",
    11,
    0,
    100,
    1,
    "How far the icon sits from the card's left edge.",
  ),
  cardPadding: number(
    "Cards",
    "Card padding",
    10,
    0,
    60,
    1,
    "Space at the card's right edge.",
  ),
  cardTitleSize: number(
    "Cards",
    "Card title",
    12.5,
    4,
    48,
    0.5,
    "The title's font size.",
  ),
  cardSubtitleSize: number(
    "Cards",
    "Card subtitle",
    11,
    4,
    48,
    0.5,
    "The subtitle's font size.",
  ),
  cardValueSize: number(
    "Cards",
    "Card value",
    12,
    4,
    48,
    0.5,
    "The value's font size.",
  ),
  cardStripeWidth: number(
    "Cards",
    "Stripe width",
    3,
    0,
    20,
    0.5,
    "The colour stripe down the card's left edge (0: none).",
  ),
  cardStripeInset: number(
    "Cards",
    "Stripe inset",
    7,
    0,
    100,
    1,
    "How far the stripe stops short of the card's top and bottom.",
  ),
  cardConnectors: choice(
    "Cards",
    "Card connectors",
    "dots",
    ["dots", "arrows", "both"],
    'Where edges meet a card: port "dots", "arrows" (arrowheads, at the end arrowEnd picks), or "both" (the arrowhead stops at the dot).',
  ),
  cardPortSize: number(
    "Cards",
    "Port size",
    8,
    0,
    40,
    0.5,
    "The port dots where the flow's edges meet a card (0: none).",
  ),
  cardDetailZoom: number(
    "Cards",
    "Card detail below zoom",
    0.55,
    0,
    4,
    0.01,
    "Below this zoom cards show only their title; below labelFadeZoom, no text at all.",
  ),

  // ---------------------------------------------------------------- labels
  showLabels: boolean("Labels", "Labels", true, "Draw node labels."),
  fontSize: number(
    "Labels",
    "Font size",
    11,
    4,
    48,
    0.5,
    "Base label font size, in graph units (before labelFontScale).",
  ),
  labelFontScale: number(
    "Labels",
    "Font size ×",
    1,
    0.3,
    4,
    0.05,
    "Multiplies every label's font size.",
  ),
  rootFontScale: number(
    "Labels",
    "Root font ×",
    1.2,
    0.5,
    3,
    0.05,
    "The root's label is this much bigger (and bold).",
  ),
  labelPosition: choice(
    "Labels",
    "Position",
    "auto",
    ["auto", "below", "above", "left", "right"],
    '"auto": beside nodes in horizontal trees, below everywhere else.',
  ),
  labelBackdrop: boolean(
    "Labels",
    "Backdrop",
    true,
    "A dark backdrop behind labels, for contrast over edges.",
  ),
  labelFadeZoom: number(
    "Labels",
    "Fade below zoom",
    0.35,
    0,
    4,
    0.01,
    "Labels fade out below this zoom (except focused and high-priority ones).",
  ),
  labelWidth: number(
    "Labels",
    "Wrap width",
    120,
    20,
    1000,
    5,
    "Labels wrap (or cut off) at this width, in graph units (before labelWrapScale).",
  ),
  labelWrapScale: number(
    "Labels",
    "Wrap width ×",
    1,
    0.2,
    5,
    0.05,
    "Multiplies the wrap width.",
  ),
  labelOverflow: choice(
    "Labels",
    "Overflow",
    "wrap",
    ["wrap", "ellipsis"],
    "Long labels wrap onto more lines, or are cut off with an ellipsis.",
  ),

  // ---------------------------------------------------------------- edges
  edgeRouting: choice(
    "Edges",
    "Routing",
    "taxi",
    ["straight", "taxi", "round-taxi", "curved"],
    'How edges bend; radial layouts use arcs for anything but "straight". Or one added with registerEdgeRouting().',
    true,
  ),
  edgeCornerRadius: number(
    "Edges",
    "Corner radius",
    10,
    0,
    100,
    1,
    "round-taxi: how round the corners are.",
  ),
  edgeCurvature: number(
    "Edges",
    "Curvature",
    1,
    -4,
    4,
    0.05,
    "Arcs (radial layouts): how far edges bow.",
  ),
  edgeWidth: number(
    "Edges",
    "Width",
    1.6,
    0.1,
    20,
    0.1,
    "Edge width, in screen pixels.",
  ),
  edgeOpacity: number(
    "Edges",
    "Opacity",
    1,
    0,
    1,
    0.01,
    "How opaque edges are.",
  ),
  edgeLineStyle: choice(
    "Edges",
    "Line",
    "solid",
    ["solid", "dashed", "dotted", "arrows"],
    'Every edge\'s line pattern (classes can override it). "arrows": a dotted line of small chevrons pointing the way the graph flows (flowToward).',
  ),
  edgeColorMode: choice(
    "Edges",
    "Colour",
    "neutral",
    ["neutral", "source", "target"],
    '"neutral": the theme\'s edge colour; "source" or "target": the colour of the node at that end.',
  ),
  showArrows: boolean("Edges", "Arrows", true, "Draw arrowheads."),
  arrowShape: choice(
    "Edges",
    "Arrowhead",
    "triangle",
    [
      "triangle",
      "vee",
      "chevron",
      "triangle-backcurve",
      "circle",
      "square",
      "tee",
    ],
    "A built-in arrowhead, or one added with registerArrowShape().",
    true,
  ),
  arrowEnd: choice(
    "Edges",
    "Arrow at",
    "target",
    ["target", "source", "both"],
    "Which end of an edge gets the arrowhead.",
  ),
  arrowScale: number(
    "Edges",
    "Arrow size",
    0.8,
    0.1,
    5,
    0.05,
    "Arrowhead size.",
  ),
  edgeLabels: boolean(
    "Edges",
    "Edge labels",
    true,
    "Draw edge labels (an edge's `label`).",
  ),

  // ---------------------------------------------------------------- interaction
  hoverMode: choice(
    "Interaction",
    "Hover lights",
    "both",
    ["both", "ancestors", "descendants", "none"],
    "What hovering a node lights up.",
  ),
  hoverDelay: integer(
    "Interaction",
    "Hover delay",
    35,
    0,
    2000,
    5,
    "Milliseconds before hover lineage shows, so sweeping across the graph doesn't flicker.",
  ),
  lineageColor: choice(
    "Interaction",
    "Lineage colour",
    "theme",
    ["theme", "edge"],
    '"theme": lit lineage edges take the theme\'s ancestors and descendants colours. "edge": they keep their own colour (class rules, edgeColorMode) and are only widened and flowing.',
  ),
  pinSelectionLineage: boolean(
    "Interaction",
    "Pin selection",
    true,
    "Keep the selected node's lineage lit after the pointer leaves it.",
  ),
  animateFlow: boolean(
    "Interaction",
    "Flow",
    true,
    "Light pulses travel along lit edges.",
  ),
  flowToward: choice(
    "Interaction",
    "Flow toward",
    "target",
    ["target", "source"],
    "Which way the pulses travel.",
  ),
  flowSpeed: number(
    "Interaction",
    "Flow speed",
    1,
    0,
    10,
    0.1,
    "How fast the pulses travel.",
  ),
  dimOpacity: number(
    "Interaction",
    "Dimmed opacity",
    0.18,
    0,
    1,
    0.01,
    "How visible everything outside a lit lineage or highlight stays.",
  ),
  nodesDraggable: boolean(
    "Interaction",
    "Drag nodes",
    true,
    "Nodes can be dragged (the physics mode decides what follows).",
  ),
  smoothZoom: boolean(
    "Interaction",
    "Smooth zoom",
    true,
    "Wheel zoom glides instead of stepping.",
  ),
  zoomSpeed: number(
    "Interaction",
    "Zoom speed",
    1,
    0.1,
    5,
    0.05,
    "Wheel zoom sensitivity.",
  ),
  minZoom: number(
    "Interaction",
    "Min zoom",
    0.005,
    0.0001,
    1,
    0.001,
    "How far out you can zoom.",
  ),
  maxZoom: number(
    "Interaction",
    "Max zoom",
    4,
    0.1,
    100,
    0.1,
    "How far in you can zoom.",
  ),
  maxFitZoom: number(
    "Interaction",
    "Max fit zoom",
    1.6,
    0.05,
    100,
    0.05,
    "Fitting the view never zooms in past this.",
  ),
  fitPadding: number(
    "Interaction",
    "Fit padding",
    40,
    0,
    500,
    1,
    "Space around the graph when fitting the view (screen pixels).",
  ),
  focusPadding: number(
    "Interaction",
    "Focus padding",
    60,
    0,
    500,
    1,
    "focusOn(): space around the nodes (screen pixels).",
  ),
  focusMaxZoom: number(
    "Interaction",
    "Focus max zoom",
    2,
    0.05,
    100,
    0.05,
    "focusOn() never zooms in past this.",
  ),
  smartFitMinZoom: number(
    "Interaction",
    "Smart fit below",
    0.3,
    0,
    4,
    0.01,
    'fit: "smart" opens on the root instead when fitting would zoom out below this…',
  ),
  smartFitMinNodes: integer(
    "Interaction",
    "Smart fit over",
    80,
    0,
    100000,
    1,
    "…and the graph has more nodes than this…",
  ),
  smartFitZoom: number(
    "Interaction",
    "Smart fit zoom",
    0.6,
    0.05,
    4,
    0.05,
    "…at this zoom.",
  ),
  doubleTapMs: integer(
    "Interaction",
    "Double tap",
    300,
    50,
    2000,
    10,
    "Most milliseconds between the taps of a double tap.",
  ),
  longPressMs: integer(
    "Interaction",
    "Long press",
    550,
    100,
    5000,
    10,
    "Milliseconds a touch is held before it counts as a context tap.",
  ),
  dragThresholdMouse: number(
    "Interaction",
    "Drag after (mouse)",
    4,
    0,
    50,
    1,
    "Pixels a mouse moves before a press becomes a drag.",
  ),
  dragThresholdPen: number(
    "Interaction",
    "Drag after (pen)",
    6,
    0,
    50,
    1,
    "Pixels a pen moves before a press becomes a drag.",
  ),
  dragThresholdTouch: number(
    "Interaction",
    "Drag after (touch)",
    10,
    0,
    50,
    1,
    "Pixels a finger moves before a press becomes a drag.",
  ),
  panInertia: number(
    "Interaction",
    "Pan glide",
    0.28,
    0,
    3,
    0.01,
    "How long the view glides after a flick (seconds; 0: it stops dead).",
  ),
  flickMinSpeed: number(
    "Interaction",
    "Flick speed",
    120,
    0,
    5000,
    10,
    "Pixels per second a pan must be moving at release to glide.",
  ),
  canvasBackground: {
    type: "string",
    group: "Interaction",
    label: "Background",
    default: "none",
    hint: '"dots" or "grid": a pattern on the canvas wrapper that follows pan and zoom (see syncBackground). Anything else is left alone.',
  },
  backgroundCellSize: number(
    "Interaction",
    "Background cell",
    26,
    4,
    200,
    1,
    "The background pattern's cell at zoom 1 (graph units).",
  ),

  // ---------------------------------------------------------------- motion
  animationsEnabled: boolean(
    "Motion",
    "Animations",
    true,
    "Animate changes (off: everything snaps).",
  ),
  animationDuration: integer(
    "Motion",
    "Duration",
    450,
    0,
    5000,
    10,
    "About how long a transition takes (milliseconds).",
  ),
  animationEasing: choice(
    "Motion",
    "Feel",
    "smooth",
    ["smooth", "snappy", "bouncy", "linear"],
    "How motion feels, or one added with registerEasing().",
    true,
  ),
  growNewGraphs: boolean(
    "Motion",
    "Grow new graphs",
    true,
    "A brand-new graph grows out of its root level by level.",
  ),
  growStagger: number(
    "Motion",
    "Grow stagger",
    0.18,
    0,
    2,
    0.01,
    "Delay per level while growing, as a share of the duration.",
  ),
  growMaxDelay: number(
    "Motion",
    "Grow max delay",
    1.4,
    0,
    10,
    0.05,
    "The longest any level waits, as a share of the duration.",
  ),
  maxAnimatedNodes: integer(
    "Motion",
    "Animate up to",
    5000,
    0,
    1000000,
    100,
    "Graphs bigger than this snap instead of morphing.",
  ),
  maxStaggeredNodes: integer(
    "Motion",
    "Grow up to",
    800,
    0,
    1000000,
    50,
    "Graphs bigger than this appear at once instead of growing level by level.",
  ),

  // ---------------------------------------------------------------- styling hooks
  nodeStyle: {
    type: "function",
    nullable: true,
    default: null,
    group: "Styling",
    label: "Node style hook",
    hint: "(node, style) => changes: return any style fields to change for this node (after classes and node.style).",
  },
  edgeStyle: {
    type: "function",
    nullable: true,
    default: null,
    group: "Styling",
    label: "Edge style hook",
    hint: "(edge, style) => changes: return any style fields to change for this edge (after classes and edge.style).",
  },
});

/**
 * @typedef {import('tether/index.js').LayoutSettings & {
 *   nodeLook: "icon" | "card", cardWidth: number, cardHeight: number, cardIconSize: number, cardIconInset: number,
 *   cardPadding: number, cardTitleSize: number, cardSubtitleSize: number, cardValueSize: number,
 *   cardStripeWidth: number, cardStripeInset: number, cardPortSize: number, cardDetailZoom: number,
 *   cardConnectors: "dots" | "arrows" | "both",
 *   nodeSize: number, nodeSizeScale: number, rootSizeScale: number, nodeShape: string, tintNodeFill: boolean,
 *   tintFillAlpha: number, nodeBorderWidth: number, rootBorderBoost: number, showIcons: boolean,
 *   showLabels: boolean, fontSize: number, labelFontScale: number, rootFontScale: number,
 *   labelPosition: "auto" | "below" | "above" | "left" | "right", labelBackdrop: boolean, labelFadeZoom: number,
 *   labelWidth: number, labelWrapScale: number, labelOverflow: "wrap" | "ellipsis",
 *   edgeRouting: string, edgeCornerRadius: number, edgeCurvature: number, edgeWidth: number, edgeOpacity: number,
 *   edgeLineStyle: "solid" | "dashed" | "dotted" | "arrows", edgeColorMode: "neutral" | "source" | "target",
 *   showArrows: boolean, arrowShape: string, arrowEnd: "target" | "source" | "both", arrowScale: number,
 *   edgeLabels: boolean,
 *   hoverMode: "both" | "ancestors" | "descendants" | "none", hoverDelay: number, lineageColor: "theme" | "edge", pinSelectionLineage: boolean,
 *   animateFlow: boolean, flowToward: "target" | "source", flowSpeed: number, dimOpacity: number,
 *   nodesDraggable: boolean, smoothZoom: boolean, zoomSpeed: number, minZoom: number, maxZoom: number,
 *   maxFitZoom: number, fitPadding: number, focusPadding: number, focusMaxZoom: number, smartFitMinZoom: number,
 *   smartFitMinNodes: number, smartFitZoom: number, doubleTapMs: number, longPressMs: number,
 *   dragThresholdMouse: number, dragThresholdPen: number, dragThresholdTouch: number, panInertia: number,
 *   flickMinSpeed: number, canvasBackground: string, backgroundCellSize: number,
 *   animationsEnabled: boolean, animationDuration: number, animationEasing: string, growNewGraphs: boolean,
 *   growStagger: number, growMaxDelay: number, maxAnimatedNodes: number, maxStaggeredNodes: number,
 *   nodeStyle: ((node: import('./graph-view.js').GraphNode, style: import('./style.js').NodeStyle) =>
 *     Partial<import('./style.js').NodeStyle> | void) | null,
 *   edgeStyle: ((edge: import('./graph-view.js').GraphEdge, style: import('./style.js').EdgeStyle) =>
 *     Partial<import('./style.js').EdgeStyle> | void) | null,
 * }} Options
 */

/** @type {Readonly<Options>} */
export const DEFAULT_OPTIONS = Object.freeze(defaultsOf(OPTIONS_SCHEMA));

/** The options as a list, in schema order, for settings UIs: { key, type, default, min, max, step, values, label, group, hint }. */
export const OPTIONS = Object.freeze(describeSchema(OPTIONS_SCHEMA));

/**
 * `patch` checked against the schema, on top of `base` (default: the defaults).
 * @param {Partial<Options>} patch
 * @param {{ base?: Options, strict?: boolean, warn?: (message: string) => void }} [options]
 * @returns {Options}
 */
export function resolveOptions(patch, options = {}) {
  const out = resolve(OPTIONS_SCHEMA, patch, {
    scope: "Prism options",
    ...options,
  });
  // Across fields: the zoom limits must be in order (otherwise the minimum wins everywhere).
  if (out.minZoom > out.maxZoom) {
    const message = `Prism options: minZoom (${out.minZoom}) is above maxZoom (${out.maxZoom}); swapping them`;
    if (options.strict) throw new TypeError(message);
    (options.warn ?? console.warn)(message);
    [out.minZoom, out.maxZoom] = [out.maxZoom, out.minZoom];
  }
  return out;
}

/**
 * Base sizes in graph units, as of the defaults (nodeSize, fontSize and labelWidth are options now).
 * @deprecated read the options instead
 */
export const STYLE_BASE = Object.freeze({
  nodeSize: DEFAULT_OPTIONS.nodeSize,
  fontSize: DEFAULT_OPTIONS.fontSize,
  labelWidth: DEFAULT_OPTIONS.labelWidth,
});
